import { useEffect,useState } from 'react';
import { RefreshCw, FileAudio, FileSearch, ChevronRight } from 'lucide-react';
import { call } from './bridge';
import type { Overview,AudioRow } from './types';
import { number,time,jobName } from './types';
export default function ActivityView({status,start,onError,onOpen}:{status:Overview;start:(kind:string,id?:string,retry?:boolean)=>void;onError:(s:string)=>void;onOpen:(id:string,ts:number)=>void}){
  const [backlog,setBacklog]=useState<'audio'|'embedding'|null>(null),[audio,setAudio]=useState<AudioRow[]>([]),[details,setDetails]=useState(false),[pending,setPending]=useState<{id:number;thread_id:string;title:string;start_ts:number;text:string}[]>([]);const active=status.jobs.find(j=>j.state==='running');
  useEffect(()=>{if(backlog==='embedding')call<typeof pending>('pending-windows').then(setPending).catch(e=>onError(String(e)));if(backlog==='audio')call<AudioRow[]>('audio').then(setAudio).catch(e=>onError(String(e)))},[backlog,status.audioPending,onError]);
  return <section className="page activity-page"><header className="page-header"><div><h1>Seu arquivo, atualizado</h1><p>{status.last_sync_at?`Última sincronização ${new Date(status.last_sync_at*1000).toLocaleString('pt-BR')}`:'A primeira sincronização está por fazer'}</p><div className="archive-counts">{number(status.messages)} mensagens <span/> {number(status.threads)} conversas</div></div><button className="primary" onClick={()=>start('sync')} disabled={!!active}><RefreshCw size={20}/>Sincronizar agora</button></header>
  <div className="backlog-grid"><article className="backlog-card"><FileAudio size={34}/><div><h2>Áudios para transcrever</h2><strong className="metric">{number(status.audioPending)}</strong><p>{number(status.audioAvailable)} disponíveis · {number(status.audioUnavailable)} arquivos indisponíveis</p></div><p>Transforme áudios em texto para ler e buscar.</p><div className="button-row"><button className="primary" onClick={()=>start('transcribe')} disabled={!!active||!status.audioAvailable}>Transcrever pendentes</button><button onClick={()=>setBacklog(backlog==='audio'?null:'audio')}>Ver áudios</button></div></article>
  <article className="backlog-card"><FileSearch size={34}/><div><h2>Conteúdo fora da busca por significado</h2><strong className="metric">{number(status.pendingSegments)} trechos</strong><p>{number(status.affectedMessages)} mensagens afetadas</p></div><p>A busca por texto continua disponível.</p><div className="button-row"><button className="primary" onClick={()=>start('embed')} disabled={!!active||!status.pendingSegments}>Gerar embeddings</button><button onClick={()=>setBacklog(backlog==='embedding'?null:'embedding')}>Ver pendências</button></div></article></div>
  {backlog?<section className="panel"><h2>{backlog==='audio'?'Áudios do arquivo':'Trechos sem embeddings'}</h2>{backlog==='audio'?<><p className="muted">Até 500 gravações mais recentes. Áudios ausentes precisam ser recuperados da fonte.</p><div className="audio-list">{audio.map(a=><div key={a.id}><button className="link" onClick={()=>onOpen(a.thread_id,a.ts)}>{a.thread_title} · {time(a.ts)}</button><span>{a.done?'Transcrito':a.availability==='available'?'Disponível':a.availability??'Disponibilidade desconhecida'}</span><button disabled={!!active||a.availability!=='available'||!!a.done} onClick={()=>start('transcribe',a.id,a.transcription_status?.includes('error'))}>{a.transcription_status?.includes('error')?'Tentar novamente':'Transcrever'}</button></div>)}</div><button onClick={()=>start('transcribe',undefined,true)} disabled={!!active}>Tentar novamente os áudios com erro</button></>:<><p className="muted">Até 200 trechos mais recentes no modelo selecionado.</p>{pending.map(w=><button className="pending-window" key={w.id} onClick={()=>onOpen(w.thread_id,w.start_ts)}><strong>{w.title}</strong><p>{w.text.slice(0,240)}</p></button>)}</>}</section>:null}
  {active?<section className="panel running-job" aria-live="polite"><h2>{jobName[active.kind]} em andamento</h2>{active.total?<><progress value={active.done??0} max={active.total}/><p>{active.done??0} de {active.total} trechos</p></>:<div className="indeterminate-progress"/>}<p className="muted">{active.detail}</p><button onClick={()=>call('cancel-job').catch(e=>onError(String(e)))}>Cancelar</button></section>:null}
  <section className="panel"><h2>Atividade recente</h2>{status.jobs.length?status.jobs.map(j=><div className="history-row" key={j.id}><time>{time(j.startedAt/1000)}</time><span className={`status-dot ${j.state}`}/><div>{jobName[j.kind]} · {({running:'Em andamento',done:'Concluída',failed:'Falhou',cancelled:'Cancelada',interrupted:'Interrompida'} as Record<string,string>)[j.state]??j.state}{details?<p className="muted">{j.detail}</p>:null}</div>{j.state==='failed'||j.state==='interrupted'?<button onClick={()=>start(j.kind,j.messageId,j.retry)}>Tentar novamente</button>:null}</div>):<p className="muted">As operações que você iniciar aparecerão aqui.</p>}<button className="link" onClick={()=>setDetails(!details)}>Ver detalhes <ChevronRight size={16}/></button></section></section>
}
