import { useCallback,useEffect,useState } from 'react';
import { Search,MessageSquare,Activity,Settings,ShieldCheck,X,ArrowUpCircle } from 'lucide-react';
import { call,native,shell } from './bridge';
import type { Overview,Thread,Person,Page } from './types';
import { number } from './types';
import SearchView from './SearchView';
import ConversationsView from './ConversationsView';
import ActivityView from './ActivityView';
import SettingsView from './SettingsView';
export default function App(){
  const [page,setPage]=useState<Page>('search'),[status,setStatus]=useState<Overview|null>(null),[threads,setThreads]=useState<Thread[]>([]),[people,setPeople]=useState<Person[]>([]),[error,setError]=useState(''),[conversation,setConversation]=useState<{id:string;ts?:number}|undefined>(),[searchThread,setSearchThread]=useState<string|undefined>(),[update,setUpdate]=useState(''),[settingsSection,setSettingsSection]=useState('general');
  const onError=useCallback((s:string)=>setError(s.replace(/^Error: /,'')),[]);
  const refresh=useCallback(async()=>{try{const [s,t,p]=await Promise.all([call<Overview>('overview'),call<Thread[]>('threads'),call<Person[]>('people')]);setStatus(s);setThreads(t);setPeople(p)}catch(e){onError(String(e))}},[onError]);
  useEffect(()=>{void refresh();const timer=setInterval(()=>{void refresh()},2500);return()=>clearInterval(timer)},[refresh]);
  useEffect(()=>{if(!native)return;void Promise.all([shell<{configured:boolean}>('update_info'),call<{values:Record<string,unknown>}>('settings')]).then(async([info,settings])=>{if(info.configured&&settings.values.desktop_check_updates){const u=await shell<{version:string}|null>('check_update');if(u)setUpdate(u.version)}}).catch(()=>{})},[]);
  const start=useCallback((kind:string,messageId?:string,retry=false)=>{void call('start-job',{kind,retry,...(messageId?{messageId}:{})}).then(()=>{setPage('activity');return refresh()}).catch(e=>onError(String(e)))},[refresh,onError]);
  function open(id:string,ts?:number){setConversation({id,ts});setPage('conversations')}
  const nav:[[Page,string,typeof Search],...Array<[Page,string,typeof Search]>]=[['search','Buscar',Search],['conversations','Conversas',MessageSquare],['activity','Atividade',Activity],['settings','Ajustes',Settings]];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><MessageSquare size={23}/></div><span>WhatMCP</span></div><nav aria-label="Navegação principal">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'selected':''} onClick={()=>{setPage(id);if(id==='settings')setSettingsSection('general')}}><Icon size={21}/>{label}{id==='activity'&&status?.jobs.some(j=>j.state==='running')?<span className="working-dot"/>:null}</button>)}</nav><div className="sidebar-bottom"><div className="local-status"><ShieldCheck size={18}/><span>{status?.demo?'Demonstração local':'Arquivo local'}</span></div>{status?<small>{number(status.messages)} mensagens · {number(status.threads)} conversas</small>:null}<small className="privacy-caption">Suas conversas, no seu computador.</small></div></aside><main>{status?.demo?<div className="demo-banner">Demonstração · mensagens fictícias <button onClick={()=>setPage('settings')}>Escolher meu arquivo</button></div>:null}{update?<div className="update-banner"><ArrowUpCircle size={18}/>Versão {update} disponível<button onClick={()=>{setSettingsSection('updates');setPage('settings')}}>Ver atualização</button></div>:null}{error?<div className="error-banner" role="alert"><span>{error}</span><button className="icon-button" aria-label="Fechar aviso" onClick={()=>setError('')}><X size={18}/></button></div>:null}{!status?<div className="page"><h1>Abrindo seu arquivo…</h1><p>Preparando o WhatMCP.</p><button onClick={()=>refresh()}>Tentar novamente</button></div>:page==='search'?<SearchView key={searchThread??'all'} threads={threads} people={people} initialThread={searchThread} onOpen={open} onError={onError} onTranscribe={id=>start('transcribe',id)}/>:page==='conversations'?<ConversationsView threads={threads} initial={conversation} onSearch={title=>{setSearchThread(title);setPage('search')}} onError={onError} onTranscribe={id=>start('transcribe',id)}/>:page==='activity'?<ActivityView status={status} start={start} onError={onError} onOpen={open}/>:<SettingsView initialSection={settingsSection} status={status} refresh={refresh} start={start} onError={onError}/>}</main></div>
}
