import { useEffect,useState } from 'react';
import { listen } from '@tauri-apps/api/event';
import { Download,RefreshCw } from 'lucide-react';
import { native,shell } from './bridge';
export default function UpdatePanel({busy,onError}:{busy:boolean;onError:(s:string)=>void}){
  const [info,setInfo]=useState({version:'0.3.0',configured:false}),[update,setUpdate]=useState<{version:string;notes:string}|null>(null),[checking,setChecking]=useState(false),[installing,setInstalling]=useState(false),[checked,setChecked]=useState(false),[progress,setProgress]=useState<{downloaded:number;total:number|null}>({downloaded:0,total:null}),[confirm,setConfirm]=useState(false);
  useEffect(()=>{if(!native)return;shell<typeof info>('update_info').then(setInfo).catch(e=>onError(String(e)));let off:(()=>void)|undefined;void listen<typeof progress>('update-progress',e=>setProgress(e.payload)).then(v=>{off=v});return()=>off?.()},[onError]);
  async function check(){setChecking(true);try{setUpdate(await shell('check_update'));setChecked(true)}catch(e){onError(String(e))}finally{setChecking(false)}}
  async function install(){if(!update)return;setConfirm(false);setInstalling(true);try{await shell('install_update',{version:update.version})}catch(e){onError(String(e));setInstalling(false)}}
  return <div className="settings-section"><h2>Atualizações</h2><p>WhatMCP {info.version}</p><p className="muted">Uma atualização inclui o app, o runtime e o coletor. Seu arquivo de mensagens e suas configurações permanecem na pasta de dados.</p>{!info.configured?<div className="notice">Este build ainda não está conectado a um canal de atualizações. A chave pública e os pacotes assinados serão configurados antes da primeira release.</div>:<><button onClick={check} disabled={checking||installing}><RefreshCw size={17}/>{checking?'Verificando…':'Verificar atualizações'}</button>{checked&&!update?<p>Você está na versão mais recente.</p>:null}{update?<article className="panel"><h3>Versão {update.version} disponível</h3><pre className="release-notes">{update.notes||'Sem notas de versão.'}</pre>{busy?<p className="notice">Conclua ou cancele a atividade atual antes de atualizar.</p>:null}<button className="primary" disabled={busy||installing} onClick={()=>setConfirm(true)}><Download size={17}/>Baixar e instalar</button></article>:null}</>}{installing?<><progress value={progress.total?progress.downloaded:undefined} max={progress.total??1}/><p>Baixando atualização verificada… O app será reiniciado.</p></>:null}{confirm?<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="update-title"><h2 id="update-title">Instalar a atualização?</h2><p>O app vai fechar e reiniciar na versão {update?.version}. Suas mensagens e configurações serão preservadas.</p><div className="button-row"><button onClick={()=>setConfirm(false)}>Agora não</button><button className="primary" onClick={install}>Instalar e reiniciar</button></div></div></div>:null}</div>
}
